spring.data.mongodb.uri=mongodb://localhost:27017/finance_dashboard
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
master.encryption.key=32876772768d39f69280018e32f09c0d77980f1277e57829c70e2305c53d78e1
app.base-url=http://localhost:8080
